FROM cypress/included:cypress-12.17.4-node-20.5.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1

ARG CUCUMBER_JSON_FORMATTER_RELEASE=v19.0.0
ARG UUID=5555
ARG GGID=5555

RUN apt-get update
RUN apt -y install wget \
    curl

RUN wget https://github.com/cucumber/json-formatter/releases/download/$CUCUMBER_JSON_FORMATTER_RELEASE/cucumber-json-formatter-linux-amd64 -q -O /usr/bin/cucumber-json-formatter
RUN chmod +x /usr/bin/cucumber-json-formatter

RUN npm install -g cypress-xpath@2.0.1

RUN usermod -u $UUID -g $GGID node

ENTRYPOINT ["cypress", "run"]